### PR TITLE
Added udev rule

### PR DESCRIPTION
**Pull request by hilary-luo**
Ported udev rule from noetic branch to humble branch

### CODE REVIEW

**Review by tonybaltovski — APPROVED** [review]

**Review by berndpfrommer — COMMENTED** [review]
I'd like to better understand how this file is used, as it is not directly referenced in the CMakefile? Currently udev files (if necessary) are created manually as per [these instructions](https://github.com/ros-drivers/flir_camera_driver/blob/humble-devel/spinnaker_camera_driver/docs/linux_setup_flir.md)

**Comment by tonybaltovski** [comment]
It gets added to the debian packaging after blooming like here: https://github.com/ros-drivers-gbp/flir_camera_driver-release/tree/debian/noetic/spinnaker_camera_driver/debian and will automatically be installed into `/usr/lib/udev/rules.d` as `60-ros-humble-spinnaker-camera-driver.rules`.

**Review by berndpfrommer — COMMENTED** [review]
Can we also support vendor ID 0x1724 then? That's Teledyne. That way we cover the same hardware as the SDK:
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="1e10", GROUP="flirimaging"
SUBSYSTEM=="usb", ATTRS{idVendor}=="1724", GROUP="flirimaging"
```
And is there a specific reason to set the mode to 0666? Wouldn't that give read/write permissions to "other", i.e. non-members of the flirimaging group?

**Comment by tonybaltovski** [comment]
For the `666` permissions, it would allow non-group access so you don't have to add the user to group.

**Comment by berndpfrommer** [comment]
That any user could open the camera is certainly not improving security. If somebody hacked into a robot they could look through the camera and potentially see classified stuff in the lab. If it were to me I'd leave it the way FLIR ships their SDK, which is without the 666 mode. But I don't have strong feelings about it, and I can understand if Clearpath does not want to deal with customers struggling with denied camera access. I leave it up to you to decide.
That's it from my end, I think the PR is good to proceed.

**Comment by tonybaltovski** [comment]
@berndpfrommer for security, we think it is better to use '660' as you said and we will add our default user to the correct group.

**Pull request merged**
